/**
 * Java Modular Image Synthesis Toolkit (JMIST)
 * Copyright (C) 2008-2013 Bradley W. Kimmel
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
package ca.eandb.jmist.framework.lens;

import ca.eandb.jmist.framework.ScatteredRay;
import ca.eandb.jmist.framework.color.Color;
import ca.eandb.jmist.framework.path.EyeNode;
import ca.eandb.jmist.framework.path.EyeTerminalNode;
import ca.eandb.jmist.framework.path.PathInfo;
import ca.eandb.jmist.math.HPoint3;
import ca.eandb.jmist.math.Point2;
import ca.eandb.jmist.math.Point3;
import ca.eandb.jmist.math.Ray3;
import ca.eandb.jmist.math.Vector3;

/**
 * A <code>Lens</code> that projects the scene onto a cylindrical virtual
 * screen.
 * @author Brad Kimmel
 */
public final class PanoramicLens extends AbstractLens {

  /** Serialization version ID. */
  private static final long serialVersionUID = 9079096932171202826L;

  /** The default horizontal field of view (in radians). */
  public static final double DEFAULT_HORIZONTAL_FIELD_OF_VIEW = Math.PI;

  /** The default vertical field of view (in radians). */
  public static final double DEFAULT_VERTICAL_FIELD_OF_VIEW = Math.PI / 2.0;

  /** Horizontal field of view (in radians). */
  private final double hfov;

  /** Height of the virtual image plane. */
  private final double height;

  /**
   * Creates a new <code>PanoramicLens</code>.
   */
  public PanoramicLens() {
    this(DEFAULT_HORIZONTAL_FIELD_OF_VIEW, DEFAULT_VERTICAL_FIELD_OF_VIEW);
  }

  /**
   * Creates a new <code>PanoramicLens</code>.
   * @param hfov The horizontal field of view (in radians).
   */
  public PanoramicLens(double hfov) {
    this(hfov, DEFAULT_VERTICAL_FIELD_OF_VIEW);
  }

  /**
   * Creates a new <code>PanoramicLens</code>.
   * @param hfov The horizontal field of view (in radians).
   * @param vfov The vertical field of view (in radians).
   */
  public PanoramicLens(double hfov, double vfov) {
    this.hfov = hfov;
    this.height = 2.0 * Math.tan(vfov / 2.0);
  }

  @Override
  public EyeNode sample(Point2 p, PathInfo pathInfo, double ru, double rv,
      double rj) {
    return new Node(p, pathInfo, ru, rv, rj);
  }

  /** An <code>EyeNode</code> generated by a <code>PanoramicLens</code>. */
  private final class Node extends EyeTerminalNode {

    /** Projected point on the image plane. */
    private final Point2 pointOnImagePlane;

    /**
     * Creates a <code>Node</code>.
     * @param pointOnImagePlane The <code>Point2</code> on the image plane.
     * @param pathInfo The <code>PathInfo</code> describing the context for
     *     this node.
     */
    public Node(Point2 pointOnImagePlane, PathInfo pathInfo, double ru, double rv, double rj) {
      super(pathInfo, ru, rv, rj);
      this.pointOnImagePlane = pointOnImagePlane;
    }

    @Override
    public ScatteredRay sample(double ru, double rv, double rj) {
      Point2 p = pointOnImagePlane;
      double theta = (p.x() - 0.5) * hfov;
      Vector3 v = new Vector3(
          Math.sin(theta),
          (0.5 - p.y()) * height,
          -Math.cos(theta));
      double r = v.length();
      Ray3 ray = new Ray3(Point3.ORIGIN, v.divide(r));
      Color color = getWhite();
      double pdf = (r * r * r * r) / (hfov * height);
      return ScatteredRay.diffuse(ray, color, pdf);
    }

    @Override
    public Color scatter(Vector3 v) {
      return getGray(getPDF(v));
    }

    @Override
    public Point2 project(HPoint3 x) {
      Ray3 ray = new Ray3(Point3.ORIGIN, x);
      Vector3 v = ray.direction();
      double theta = Math.atan2(v.x(), -v.z());
      if (Math.abs(theta) > 0.5 * hfov) {
        return null;
      }
      double h = v.y() / Math.hypot(v.x(), v.z());
      if (Math.abs(h) > 0.5 * height) {
        return null;
      }
      return new Point2(
          0.5 + theta / hfov,
          0.5 - h / height);
    }

    @Override
    public double getCosine(Vector3 v) {
      return Math.hypot(v.x(), v.z()) / v.length();
    }

    @Override
    public HPoint3 getPosition() {
      return Point3.ORIGIN;
    }

    @Override
    public double getPDF() {
      return 1.0;
    }

    @Override
    public boolean isSpecular() {
      return true;
    }

    @Override
    public double getPDF(Vector3 v) {
      double theta = Math.atan2(v.x(), -v.z());
      if (Math.abs(theta) > 0.5 * hfov) {
        return 0.0;
      }
      double h = v.y() / Math.hypot(v.x(), v.z());
      if (Math.abs(h) > 0.5 * height) {
        return 0.0;
      }
      double u = getCosine(v);
      return 1.0 / (u * u * u * u * hfov * height);
    }

  }

}
