/*
 * ProgressTreePanel.java
 *
 * Created on October 28, 2007, 1:16 AM
 */

package org.jmist.toolkit.ui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author  bkimmel
 */
public class ProgressTreePanel extends javax.swing.JPanel {

	/** Creates new form ProgressTreePanel */
	public ProgressTreePanel() {
		this.top = new ProgressNode("");
		initComponents();
	}

	/**
	 * Creates a new <code>ProgressTreePanel</code>.
	 * @param title The title of the root task.
	 */
	public ProgressTreePanel(String title) {
		this.top = new ProgressNode(title);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		javax.swing.JPanel progressNodeComponent;

		parentButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		childrenTable = new javax.swing.JTable();
		progressNodePanel = new javax.swing.JPanel();
		progressNodeComponent = getTopNodeComponent();
		rootButton = new javax.swing.JButton();

		parentButton.setText("<<");
		parentButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				parentButtonActionPerformed(evt);
			}
		});

		childrenTable.setModel(getTableModel());
		childrenTable.getColumn("Progress").setCellRenderer(new ProgressTableCellRenderer());
		childrenTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				childrenTableMouseClicked(evt);
			}
		});

		jScrollPane1.setViewportView(childrenTable);

		javax.swing.GroupLayout progressNodeComponentLayout = new javax.swing.GroupLayout(progressNodeComponent);
		progressNodeComponent.setLayout(progressNodeComponentLayout);
		progressNodeComponentLayout.setHorizontalGroup(
			progressNodeComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 408, Short.MAX_VALUE)
		);
		progressNodeComponentLayout.setVerticalGroup(
			progressNodeComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 59, Short.MAX_VALUE)
		);

		javax.swing.GroupLayout progressNodePanelLayout = new javax.swing.GroupLayout(progressNodePanel);
		progressNodePanel.setLayout(progressNodePanelLayout);
		progressNodePanelLayout.setHorizontalGroup(
			progressNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addComponent(progressNodeComponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		progressNodePanelLayout.setVerticalGroup(
			progressNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addComponent(progressNodeComponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);

		rootButton.setText("O");
		rootButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rootButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
					.addComponent(progressNodePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout.createSequentialGroup()
						.addComponent(rootButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(parentButton))
					.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
				.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addComponent(progressNodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(parentButton)
					.addComponent(rootButton))
				.addContainerGap())
		);
	}// </editor-fold>//GEN-END:initComponents

	private void childrenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_childrenTableMouseClicked

		if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1 && evt.getClickCount() == 2) {

			int selectedRow = this.childrenTable.getSelectedRow();

			if (selectedRow >= 0) {
				evt.consume();
				this.moveToChild(selectedRow);
			}

		}

	}//GEN-LAST:event_childrenTableMouseClicked

	private void rootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootButtonActionPerformed
		this.moveToRoot();
	}//GEN-LAST:event_rootButtonActionPerformed

	private void parentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentButtonActionPerformed
		this.moveToParent();
	}//GEN-LAST:event_parentButtonActionPerformed

	private class ProgressTableCellRenderer implements TableCellRenderer {

		/* (non-Javadoc)
		 * @see javax.swing.table.TableCellRenderer#getTableCellRendererComponent(javax.swing.JTable, java.lang.Object, boolean, boolean, int, int)
		 */
		@Override
		public Component getTableCellRendererComponent(JTable table,
				Object value, boolean isSelected, boolean hasFocus, int row, int column) {

			return (JProgressBar) value;

		}

	}

	private JPanel getTopNodeComponent() {
		return (JPanel) this.top.getComponent();
	}

	private TableModel getTableModel() {
		return this.top;
	}

	private void refresh() {

		JComponent progressNodeComponent = this.getTopNodeComponent();

		this.progressNodePanel.removeAll();

		javax.swing.GroupLayout progressNodePanelLayout = new javax.swing.GroupLayout(progressNodePanel);
		progressNodePanel.setLayout(progressNodePanelLayout);
		progressNodePanelLayout.setHorizontalGroup(
			progressNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addComponent(progressNodeComponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		progressNodePanelLayout.setVerticalGroup(
			progressNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addComponent(progressNodeComponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);

		this.childrenTable.setModel(this.getTableModel());

	}

	public ProgressIndicator getRootProgressIndicator() {
		return this.getRootNode();
	}

	private ProgressNode getRootNode() {

		ProgressNode node = this.top;

		while (node.getParent() != null) {
			node = node.getParent();
		}

		return node;

	}

	private void moveToNode(ProgressNode node) {
		this.top = node;
		this.refresh();
	}

	private void moveToRoot() {
		this.moveToNode(this.getRootNode());
	}

	private void moveToParent() {

		ProgressNode parent = this.top.getParent();
		assert(parent != null);

		this.moveToNode(parent);

	}

	private void moveToChild(int index) {
		this.moveToNode(this.top.getChild(index));
	}

	private static final class ProgressNode extends AbstractTableModel implements ProgressIndicator {

		public ProgressNode(String title) {
			this.title = title;
			this.parent = null;
		}

		private ProgressNode(String title, ProgressNode parent) {
			this.title = title;
			this.parent = parent;
		}

		/* (non-Javadoc)
		 * @see org.jmist.toolkit.ui.ProgressIndicator#addChild(java.lang.String)
		 */
		@Override
		public ProgressNode addChild(String title) {
			ProgressNode node = new ProgressNode(title, this);
			int index = this.children.size();
			this.children.add(node);
			this.fireTableRowsInserted(index, index);
			return node;
		}

		public ProgressNode getParent() {
			return this.parent;
		}

		public int getNumChildren() {
			return this.children.size();
		}

		public ProgressNode getChild(int index) {
			return this.children.get(index);
		}

		public void removeChildAt(int index) {

			assert(0 <= index && index < this.children.size());

			this.children.remove(index);
			this.fireTableRowsDeleted(index, index);

		}

		private void fireColumnChanged(int column) {
			if (this.parent != null) {
				// TODO indicate which cell changed.
				this.parent.fireTableDataChanged();
			}
		}

		public JComponent getComponent() {

			if (this.panel == null) {

				this.panel = new javax.swing.JPanel();
				this.statusLabel = new javax.swing.JLabel();
				this.titleLabel = new javax.swing.JLabel();

				this.titleLabel.setText(this.title);
				this.statusLabel.setText(this.status);

				javax.swing.JPanel progressBarPanel = new javax.swing.JPanel();

				javax.swing.GroupLayout progressBarPanelLayout = new javax.swing.GroupLayout(progressBarPanel);
				progressBarPanel.setLayout(progressBarPanelLayout);
				progressBarPanelLayout.setHorizontalGroup(
					progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGap(0, 408, Short.MAX_VALUE)
					.addComponent(this.progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
				);
				progressBarPanelLayout.setVerticalGroup(
					progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGap(0, 19, Short.MAX_VALUE)
					.addComponent(this.progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				);

				javax.swing.GroupLayout progressNodePanelLayout = new javax.swing.GroupLayout(this.panel);
				this.panel.setLayout(progressNodePanelLayout);
				progressNodePanelLayout.setHorizontalGroup(
					progressNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
					.addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
					.addComponent(progressBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
				progressNodePanelLayout.setVerticalGroup(
					progressNodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(progressNodePanelLayout.createSequentialGroup()
						.addComponent(titleLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(statusLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(progressBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

			}

			return this.panel;

		}

		/* (non-Javadoc)
		 * @see javax.swing.table.TableModel#getColumnCount()
		 */
		@Override
		public int getColumnCount() {
			return NUM_COLUMNS;
		}

		/* (non-Javadoc)
		 * @see javax.swing.table.TableModel#getRowCount()
		 */
		@Override
		public int getRowCount() {
			return this.children.size();
		}

		/* (non-Javadoc)
		 * @see javax.swing.table.TableModel#getValueAt(int, int)
		 */
		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {

			assert(rowIndex < this.children.size());

			ProgressNode node = this.children.get(rowIndex);

			switch (columnIndex) {

			case CHILDREN_COLUMN:
				return node.children.size();

			case TITLE_COLUMN:
				return node.title;

			case PROGRESS_COLUMN:
				return node.progressBar;

			case STATUS_COLUMN:
				return node.status;

			default:
				assert(false);
				return null;

			}

		}

		/* (non-Javadoc)
		 * @see javax.swing.table.AbstractTableModel#getColumnClass(int)
		 */
		@Override
		public Class<?> getColumnClass(int columnIndex) {
			return COLUMN_CLASS[columnIndex];
		}

		/* (non-Javadoc)
		 * @see javax.swing.table.AbstractTableModel#getColumnName(int)
		 */
		@Override
		public String getColumnName(int column) {
			return COLUMN_NAME[column];
		}

		private final ProgressNode			parent;
		private final List<ProgressNode>	children			= new ArrayList<ProgressNode>();

		private final JProgressBar			progressBar			= new JProgressBar();

		private final String				title;
		private String						status				= "";

		private javax.swing.JPanel			panel				= null;
		private javax.swing.JLabel			statusLabel			= null;
		private javax.swing.JLabel			titleLabel			= null;

		private static final int			NUM_COLUMNS			= 4;
		private static final int			CHILDREN_COLUMN		= 0;
		private static final int			TITLE_COLUMN		= 1;
		private static final int			PROGRESS_COLUMN		= 2;
		private static final int			STATUS_COLUMN		= 3;

		private static final Class<?>[]		COLUMN_CLASS		= { Integer.class, String.class, JProgressBar.class, String.class };
		private static final String[]		COLUMN_NAME			= { "Children", "Title", "Progress", "Status" };

		@Override
		public void removeChild(ProgressIndicator child) {

			for (int index = 0; index < this.children.size(); index++) {
				if (this.children.get(index) == child) {
					this.removeChildAt(index);
					break;
				}
			}

		}

		/* (non-Javadoc)
		 * @see org.jmist.toolkit.ui.ProgressIndicator#isCancelPending()
		 */
		@Override
		public boolean isCancelPending() {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public void setProgress(double progress) {
			this.progressBar.setStringPainted(false);
			this.setProgressBarValue((int) Math.floor(progress * 100.0), 100);
		}

		@Override
		public void setProgress(int value, int maximum) {
			this.progressBar.setString(String.format("(%d/%d)", value, maximum));
			this.progressBar.setStringPainted(true);
			this.setProgressBarValue(value, maximum);
		}

		private void setProgressBarValue(int value, int maximum) {

			this.progressBar.setIndeterminate(false);

			if (this.progressBar.getMaximum() != maximum) {
				this.progressBar.setMaximum(maximum);
			}

			this.progressBar.setValue(value);
			this.fireColumnChanged(PROGRESS_COLUMN);

		}

		@Override
		public void setProgressIndeterminant() {

			this.progressBar.setIndeterminate(true);
			this.fireColumnChanged(PROGRESS_COLUMN);

		}

		@Override
		public void setStatusText(String statusText) {

			this.status = statusText;

			if (this.statusLabel != null) {
				this.statusLabel.setText(this.status);
			}

			if (this.parent != null) {
				this.fireColumnChanged(STATUS_COLUMN);
			}

		}

	}

	/**
	 * The <code>ProgressNode</code> currently displaying at the top of this
	 * panel.
	 */
	private ProgressNode top;

	/**
	 * Serialization version ID.
	 */
	private static final long serialVersionUID = 4364840053111586849L;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTable childrenTable;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton parentButton;
	private javax.swing.JPanel progressNodePanel;
	private javax.swing.JButton rootButton;
	// End of variables declaration//GEN-END:variables

}
